# Cloud Build configuration for automatic deployment from GitHub to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/admin:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/admin:latest'
      - '.'
    timeout: 1200s

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/admin:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/admin:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'admin'
      - '--image'
      - 'gcr.io/$PROJECT_ID/admin:$COMMIT_SHA'
      - '--region'
      - 'us-central1'  # Change this to your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--port'
      - '8080'

# Build timeout
timeout: 1800s

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/admin:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/admin:latest'

# Substitutions (can be overridden)
substitutions:
  _REGION: 'us-central1'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
